version: 2.1
jobs:
  build:
     working_directory: ~/tmp
     docker:
       - image: cimg/node:14.16.1
     steps:
       - checkout
       - run: npm install
       - run: npm run lint
       - run: npm test
       - run: ssh -o StrictHostKeyChecking=no $DROPLET_USER@$DROPLET_IP 'cd production; git checkout master; git pull; npm install; npm run start:production;'
workflows:
build-deploy:
 jobs:
   - build:
       filters:
         branches:
           only: master
